version: "3.9"

volumes:
  public:

services:
  nginx:
    image: nginx:1.23-alpine
    environment:
      SERVER_NAME:
    volumes:
      - public:/public
      - ./templates:/etc/nginx/templates
    ports:
      - "4000:80"
