version: "3.9"

volumes:
  public:

services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - public:/public
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
  ngrok:
    image: ngrok/ngrok:2-alpine
    env_file:
      - .env
    command: http nginx:80
    ports:
      - "4040:4040"
